apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-facade-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-facade  # The name of your Deployment
  minReplicas: 3  # Minimum number of replicas
  maxReplicas: 6  # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target CPU utilization percentage