apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-facade
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-facade
  template:
    metadata:
      labels:
        app: api-facade
    spec:
      containers:
      - name: api-facade
        image: api-facade:latest  # This should match the tag from the local build
        imagePullPolicy: IfNotPresent  # Use the local image if available
        ports:
          - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:password@db-service:5432/stock_data"
        - name: PROMETHEUS_PUSHGATEWAY_URL
          value: "http://prometheus-service:9090"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: api-facade-service
spec:
  selector:
    app: api-facade
  ports:
    - protocol: TCP
      name: api
      port: 8080  # The port on which the API service is exposed
      targetPort: 8080  # The port on which the pod is listening for API requests
  type: ClusterIP