apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-core
  template:
    metadata:
      labels:
        app: api-core
    spec:
      containers:
      - name: api-core
        image: api-core:latest  # This should match the tag from the local build
        imagePullPolicy: IfNotPresent  # Use the local image if available
        env:
        - name: PROMETHEUS_PUSHGATEWAY_URL
          value: "http://prometheus-service:9090"