apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest  # Use the latest Prometheus image
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-storage
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yaml
          subPath: prometheus.yaml  # Maps the file directly
        args:
        - "--config.file=/etc/prometheus/prometheus.yaml"
        - "--web.listen-address=:9090"
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  ports:
    - port: 9090
  selector:
    app: prometheus